name: Deploy to azure app services
on:
  push:
     branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        working-directory: ./patisserie-back
        run: npm install

      - name: Deploy to azure App services
        uses: azure/webapps-deploy@v2
        with:
          app-name: patisserie-app
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: .